---
- name: Deploy to tomcat
  hosts: web
  become: yes
  tasks:
    - name: Copy war to tomcat
      copy:
        src: "/var/snap/jenkins/ansibleJenkins/mavenAnsible.war"
        dest: "/opt/tomcat/webapps/mavenAnsible.war"
        remote_src: no
